apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-task2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: crud-app
        image: taimoorkhan5044/crud-app:0.1.0-12d3c65
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: nginx-config
        - secretRef:
            name: crud-app-secret